server:
  port: 8989
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /
      suffix: .jsp

      http:
        multipart:
          max-file-size: 15Mb
          max-request-size: 150Mb
  http:
    encoding:
      force: true
      charset: UTF-8
mybatis:
  mapper-locations: com/baizhi/dao/*Mapper.xml
  type-aliases-package: com.baizhi.entity